version: "3.8"

services:
  frontend:
    build:
      context: .
    container_name: frontend-app
    restart: always
    ports:
      - "8080:80"
    networks:
      - shared_network

networks:
  shared_network:
    external: true
