services:
  backend:
    build:
      context: ./backend
    container_name: backend-app
    ports:
      - "3001:3001" # Changez le port selon les besoins
    depends_on:
      - mariadb
    environment:
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=database
    restart: always

  mariadb:
    image: mariadb:latest
    container_name: backend-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  frontend:
    build:
      context: ./frontend
    container_name: frontend-app
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always

volumes:
  db_data:
