services:
  # Service pour l'application Node.js
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    ports:
      - "3001:3001"  # Expose le port 3001
    environment:
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=database
    depends_on:
      - mariadb
    networks:
      - app-network

  # Service pour la base de données MariaDB
  mariadb:
    image: mariadb:11.6.2
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
    ports:
      - "3306:3306"  # Expose le port 3306
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - app-network

# Réseaux utilisés par les services
networks:
  app-network:
    driver: bridge

# Volumes pour persister les données de la base de données
volumes:
  mariadb-data:
